[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

# Monad Configuration
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 10143
bytecode_hash = "none"
cbor_metadata = false

# Compiler settings optimized for Monad
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false

# Contract size limit for Monad (128KB instead of 24KB)
# This prevents contract size warnings since Monad supports larger contracts
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.monad]
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143
optimizer = true
optimizer_runs = 1000
via_ir = true

[profile.anvil]
eth-rpc-url = "http://localhost:8545"
chain_id = 31337

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
monad_sepolia = "https://sepolia.monad.xyz"
anvil = "http://localhost:8545"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
